### ISSUE TITLE
Installtion fails:

### ISSUE THREAD

**Issue by riccardoklinger** [fidelthomet/where2#4]
Node is installed but "npm install" fails with the following message:

MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) fügen Sie den Speicherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [C:\node_apps\where2-master\node_modules\spatialite\build\binding.sln]

**Comment by fidelthomet** [comment]
Hi, where2 is based on spatialite. Please follow [these instruction](https://www.npmjs.com/package/spatialite#building-on-windows) to get it running on windows.

**Comment by riccardoklinger** [comment]
Should be stated in the https://github.com/fidelthomet/where2#prerequisites on your readme.md

But thanks for the clarification.
